package com.github.blovemaple.hura.dal;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table programeto_query_log
 */
public class ProgrametoQueryLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.cost
	 * @mbg.generated
	 */
	private Integer cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.unionid
	 * @mbg.generated
	 */
	private String unionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.query
	 * @mbg.generated
	 */
	private String query;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.section_key
	 * @mbg.generated
	 */
	private String sectionKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.has_result
	 * @mbg.generated
	 */
	private Boolean hasResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_query_log.result
	 * @mbg.generated
	 */
	private String result;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.id
	 * @return  the value of programeto_query_log.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.id
	 * @param id  the value for programeto_query_log.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.time
	 * @return  the value of programeto_query_log.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.time
	 * @param time  the value for programeto_query_log.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.cost
	 * @return  the value of programeto_query_log.cost
	 * @mbg.generated
	 */
	public Integer getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.cost
	 * @param cost  the value for programeto_query_log.cost
	 * @mbg.generated
	 */
	public void setCost(Integer cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.openid
	 * @return  the value of programeto_query_log.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.openid
	 * @param openid  the value for programeto_query_log.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.unionid
	 * @return  the value of programeto_query_log.unionid
	 * @mbg.generated
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.unionid
	 * @param unionid  the value for programeto_query_log.unionid
	 * @mbg.generated
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.query
	 * @return  the value of programeto_query_log.query
	 * @mbg.generated
	 */
	public String getQuery() {
		return query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.query
	 * @param query  the value for programeto_query_log.query
	 * @mbg.generated
	 */
	public void setQuery(String query) {
		this.query = query;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.section_key
	 * @return  the value of programeto_query_log.section_key
	 * @mbg.generated
	 */
	public String getSectionKey() {
		return sectionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.section_key
	 * @param sectionKey  the value for programeto_query_log.section_key
	 * @mbg.generated
	 */
	public void setSectionKey(String sectionKey) {
		this.sectionKey = sectionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.has_result
	 * @return  the value of programeto_query_log.has_result
	 * @mbg.generated
	 */
	public Boolean getHasResult() {
		return hasResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.has_result
	 * @param hasResult  the value for programeto_query_log.has_result
	 * @mbg.generated
	 */
	public void setHasResult(Boolean hasResult) {
		this.hasResult = hasResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_query_log.result
	 * @return  the value of programeto_query_log.result
	 * @mbg.generated
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_query_log.result
	 * @param result  the value for programeto_query_log.result
	 * @mbg.generated
	 */
	public void setResult(String result) {
		this.result = result;
	}
}