package com.github.blovemaple.hura.dal;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table programeto_login_log
 */
public class ProgrametoLoginLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.id
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.time
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.cost
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private Integer cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.code
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.openid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column programeto_login_log.unionid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	private String unionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.id
	 * @return  the value of programeto_login_log.id
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.id
	 * @param id  the value for programeto_login_log.id
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.time
	 * @return  the value of programeto_login_log.time
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.time
	 * @param time  the value for programeto_login_log.time
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.cost
	 * @return  the value of programeto_login_log.cost
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public Integer getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.cost
	 * @param cost  the value for programeto_login_log.cost
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setCost(Integer cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.code
	 * @return  the value of programeto_login_log.code
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.code
	 * @param code  the value for programeto_login_log.code
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.openid
	 * @return  the value of programeto_login_log.openid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.openid
	 * @param openid  the value for programeto_login_log.openid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column programeto_login_log.unionid
	 * @return  the value of programeto_login_log.unionid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column programeto_login_log.unionid
	 * @param unionid  the value for programeto_login_log.unionid
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}
}