package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.ProgrametoLoginLog;
import com.github.blovemaple.hura.dal.ProgrametoLoginLogExample.Criteria;
import com.github.blovemaple.hura.dal.ProgrametoLoginLogExample.Criterion;
import com.github.blovemaple.hura.dal.ProgrametoLoginLogExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ProgrametoLoginLogSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String countByExample(ProgrametoLoginLogExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("programeto_login_log");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String deleteByExample(ProgrametoLoginLogExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("programeto_login_log");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String insertSelective(ProgrametoLoginLog record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("programeto_login_log");
		if (record.getTime() != null) {
			sql.VALUES("time", "#{time,jdbcType=TIMESTAMP}");
		}
		if (record.getCost() != null) {
			sql.VALUES("cost", "#{cost,jdbcType=INTEGER}");
		}
		if (record.getCode() != null) {
			sql.VALUES("code", "#{code,jdbcType=VARCHAR}");
		}
		if (record.getOpenid() != null) {
			sql.VALUES("openid", "#{openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.VALUES("unionid", "#{unionid,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String selectByExample(ProgrametoLoginLogExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("time");
		sql.SELECT("cost");
		sql.SELECT("code");
		sql.SELECT("openid");
		sql.SELECT("unionid");
		sql.FROM("programeto_login_log");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		ProgrametoLoginLog record = (ProgrametoLoginLog) parameter.get("record");
		ProgrametoLoginLogExample example = (ProgrametoLoginLogExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("programeto_login_log");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getTime() != null) {
			sql.SET("time = #{record.time,jdbcType=TIMESTAMP}");
		}
		if (record.getCost() != null) {
			sql.SET("cost = #{record.cost,jdbcType=INTEGER}");
		}
		if (record.getCode() != null) {
			sql.SET("code = #{record.code,jdbcType=VARCHAR}");
		}
		if (record.getOpenid() != null) {
			sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.SET("unionid = #{record.unionid,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("programeto_login_log");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("time = #{record.time,jdbcType=TIMESTAMP}");
		sql.SET("cost = #{record.cost,jdbcType=INTEGER}");
		sql.SET("code = #{record.code,jdbcType=VARCHAR}");
		sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		sql.SET("unionid = #{record.unionid,jdbcType=VARCHAR}");
		ProgrametoLoginLogExample example = (ProgrametoLoginLogExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(ProgrametoLoginLog record) {
		SQL sql = new SQL();
		sql.UPDATE("programeto_login_log");
		if (record.getTime() != null) {
			sql.SET("time = #{time,jdbcType=TIMESTAMP}");
		}
		if (record.getCost() != null) {
			sql.SET("cost = #{cost,jdbcType=INTEGER}");
		}
		if (record.getCode() != null) {
			sql.SET("code = #{code,jdbcType=VARCHAR}");
		}
		if (record.getOpenid() != null) {
			sql.SET("openid = #{openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.SET("unionid = #{unionid,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table programeto_login_log
	 * @mbg.generated  Sun Dec 23 22:48:53 CST 2018
	 */
	protected void applyWhere(SQL sql, ProgrametoLoginLogExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}