package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.UserConfig;
import com.github.blovemaple.hura.dal.UserConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import com.github.blovemaple.hura.util.StringListTypeHandler;

@Mapper
public interface UserConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@SelectProvider(type = UserConfigSqlProvider.class, method = "countByExample")
	long countByExample(UserConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@DeleteProvider(type = UserConfigSqlProvider.class, method = "deleteByExample")
	int deleteByExample(UserConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@Delete({ "delete from user_config", "where openid = #{openid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@Insert({ "insert into user_config (openid, def_vortlisto_id, ", "show_query_history, hide_section_keys, ",
			"modtime)", "values (#{openid,jdbcType=VARCHAR}, #{defVortlistoId,jdbcType=BIGINT}, ",
			"#{showQueryHistory,jdbcType=BIT}, #{hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler}, ",
			"#{modtime,jdbcType=TIMESTAMP})" })
	int insert(UserConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@InsertProvider(type = UserConfigSqlProvider.class, method = "insertSelective")
	int insertSelective(UserConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@SelectProvider(type = UserConfigSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "def_vortlisto_id", property = "defVortlistoId", jdbcType = JdbcType.BIGINT),
			@Result(column = "show_query_history", property = "showQueryHistory", jdbcType = JdbcType.BIT),
			@Result(column = "hide_section_keys", property = "hideSectionKeys", typeHandler = StringListTypeHandler.class, jdbcType = JdbcType.VARCHAR),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	List<UserConfig> selectByExample(UserConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@Select({ "select", "openid, def_vortlisto_id, show_query_history, hide_section_keys, modtime", "from user_config",
			"where openid = #{openid,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "def_vortlisto_id", property = "defVortlistoId", jdbcType = JdbcType.BIGINT),
			@Result(column = "show_query_history", property = "showQueryHistory", jdbcType = JdbcType.BIT),
			@Result(column = "hide_section_keys", property = "hideSectionKeys", typeHandler = StringListTypeHandler.class, jdbcType = JdbcType.VARCHAR),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	UserConfig selectByPrimaryKey(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@UpdateProvider(type = UserConfigSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") UserConfig record, @Param("example") UserConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@UpdateProvider(type = UserConfigSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") UserConfig record, @Param("example") UserConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@UpdateProvider(type = UserConfigSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(UserConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	@Update({ "update user_config", "set def_vortlisto_id = #{defVortlistoId,jdbcType=BIGINT},",
			"show_query_history = #{showQueryHistory,jdbcType=BIT},",
			"hide_section_keys = #{hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler},",
			"modtime = #{modtime,jdbcType=TIMESTAMP}", "where openid = #{openid,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(UserConfig record);
}