package com.github.blovemaple.hura.dal;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.unionid
	 * @mbg.generated
	 */
	private String unionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nick_name
	 * @mbg.generated
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.avatar_url
	 * @mbg.generated
	 */
	private String avatarUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.country
	 * @mbg.generated
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.province
	 * @mbg.generated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.language
	 * @mbg.generated
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.addtime
	 * @mbg.generated
	 */
	private Date addtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.openid
	 * @return  the value of user.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.openid
	 * @param openid  the value for user.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.unionid
	 * @return  the value of user.unionid
	 * @mbg.generated
	 */
	public String getUnionid() {
		return unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.unionid
	 * @param unionid  the value for user.unionid
	 * @mbg.generated
	 */
	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nick_name
	 * @return  the value of user.nick_name
	 * @mbg.generated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nick_name
	 * @param nickName  the value for user.nick_name
	 * @mbg.generated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.avatar_url
	 * @return  the value of user.avatar_url
	 * @mbg.generated
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.avatar_url
	 * @param avatarUrl  the value for user.avatar_url
	 * @mbg.generated
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.country
	 * @return  the value of user.country
	 * @mbg.generated
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.country
	 * @param country  the value for user.country
	 * @mbg.generated
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.province
	 * @return  the value of user.province
	 * @mbg.generated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.province
	 * @param province  the value for user.province
	 * @mbg.generated
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.city
	 * @return  the value of user.city
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.city
	 * @param city  the value for user.city
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.language
	 * @return  the value of user.language
	 * @mbg.generated
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.language
	 * @param language  the value for user.language
	 * @mbg.generated
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.addtime
	 * @return  the value of user.addtime
	 * @mbg.generated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.addtime
	 * @param addtime  the value for user.addtime
	 * @mbg.generated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}
}