package com.github.blovemaple.hura.dal;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_config
 */
public class UserConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_config.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_config.def_vortlisto_id
	 * @mbg.generated
	 */
	private Long defVortlistoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_config.show_query_history
	 * @mbg.generated
	 */
	private Boolean showQueryHistory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_config.hide_section_keys
	 * @mbg.generated
	 */
	private List<String> hideSectionKeys;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_config.modtime
	 * @mbg.generated
	 */
	private Date modtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_config.openid
	 * @return  the value of user_config.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_config.openid
	 * @param openid  the value for user_config.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_config.def_vortlisto_id
	 * @return  the value of user_config.def_vortlisto_id
	 * @mbg.generated
	 */
	public Long getDefVortlistoId() {
		return defVortlistoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_config.def_vortlisto_id
	 * @param defVortlistoId  the value for user_config.def_vortlisto_id
	 * @mbg.generated
	 */
	public void setDefVortlistoId(Long defVortlistoId) {
		this.defVortlistoId = defVortlistoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_config.show_query_history
	 * @return  the value of user_config.show_query_history
	 * @mbg.generated
	 */
	public Boolean getShowQueryHistory() {
		return showQueryHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_config.show_query_history
	 * @param showQueryHistory  the value for user_config.show_query_history
	 * @mbg.generated
	 */
	public void setShowQueryHistory(Boolean showQueryHistory) {
		this.showQueryHistory = showQueryHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_config.hide_section_keys
	 * @return  the value of user_config.hide_section_keys
	 * @mbg.generated
	 */
	public List<String> getHideSectionKeys() {
		return hideSectionKeys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_config.hide_section_keys
	 * @param hideSectionKeys  the value for user_config.hide_section_keys
	 * @mbg.generated
	 */
	public void setHideSectionKeys(List<String> hideSectionKeys) {
		this.hideSectionKeys = hideSectionKeys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_config.modtime
	 * @return  the value of user_config.modtime
	 * @mbg.generated
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_config.modtime
	 * @param modtime  the value for user_config.modtime
	 * @mbg.generated
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}
}