package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.UserConfig;
import com.github.blovemaple.hura.dal.UserConfigExample.Criteria;
import com.github.blovemaple.hura.dal.UserConfigExample.Criterion;
import com.github.blovemaple.hura.dal.UserConfigExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserConfigSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String countByExample(UserConfigExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("user_config");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String deleteByExample(UserConfigExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("user_config");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String insertSelective(UserConfig record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("user_config");
		if (record.getOpenid() != null) {
			sql.VALUES("openid", "#{openid,jdbcType=VARCHAR}");
		}
		if (record.getDefVortlistoId() != null) {
			sql.VALUES("def_vortlisto_id", "#{defVortlistoId,jdbcType=BIGINT}");
		}
		if (record.getShowQueryHistory() != null) {
			sql.VALUES("show_query_history", "#{showQueryHistory,jdbcType=BIT}");
		}
		if (record.getHideSectionKeys() != null) {
			sql.VALUES("hide_section_keys",
					"#{hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler}");
		}
		if (record.getModtime() != null) {
			sql.VALUES("modtime", "#{modtime,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String selectByExample(UserConfigExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("openid");
		} else {
			sql.SELECT("openid");
		}
		sql.SELECT("def_vortlisto_id");
		sql.SELECT("show_query_history");
		sql.SELECT("hide_section_keys");
		sql.SELECT("modtime");
		sql.FROM("user_config");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		UserConfig record = (UserConfig) parameter.get("record");
		UserConfigExample example = (UserConfigExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("user_config");
		if (record.getOpenid() != null) {
			sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		}
		if (record.getDefVortlistoId() != null) {
			sql.SET("def_vortlisto_id = #{record.defVortlistoId,jdbcType=BIGINT}");
		}
		if (record.getShowQueryHistory() != null) {
			sql.SET("show_query_history = #{record.showQueryHistory,jdbcType=BIT}");
		}
		if (record.getHideSectionKeys() != null) {
			sql.SET("hide_section_keys = #{record.hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler}");
		}
		if (record.getModtime() != null) {
			sql.SET("modtime = #{record.modtime,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("user_config");
		sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		sql.SET("def_vortlisto_id = #{record.defVortlistoId,jdbcType=BIGINT}");
		sql.SET("show_query_history = #{record.showQueryHistory,jdbcType=BIT}");
		sql.SET("hide_section_keys = #{record.hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler}");
		sql.SET("modtime = #{record.modtime,jdbcType=TIMESTAMP}");
		UserConfigExample example = (UserConfigExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(UserConfig record) {
		SQL sql = new SQL();
		sql.UPDATE("user_config");
		if (record.getDefVortlistoId() != null) {
			sql.SET("def_vortlisto_id = #{defVortlistoId,jdbcType=BIGINT}");
		}
		if (record.getShowQueryHistory() != null) {
			sql.SET("show_query_history = #{showQueryHistory,jdbcType=BIT}");
		}
		if (record.getHideSectionKeys() != null) {
			sql.SET("hide_section_keys = #{hideSectionKeys,jdbcType=VARCHAR,typeHandler=com.github.blovemaple.hura.util.StringListTypeHandler}");
		}
		if (record.getModtime() != null) {
			sql.SET("modtime = #{modtime,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("openid = #{openid,jdbcType=VARCHAR}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_config
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, UserConfigExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}