package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.User;
import com.github.blovemaple.hura.dal.UserExample.Criteria;
import com.github.blovemaple.hura.dal.UserExample.Criterion;
import com.github.blovemaple.hura.dal.UserExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String countByExample(UserExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("user");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String deleteByExample(UserExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("user");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String insertSelective(User record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("user");
		if (record.getOpenid() != null) {
			sql.VALUES("openid", "#{openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.VALUES("unionid", "#{unionid,jdbcType=VARCHAR}");
		}
		if (record.getNickName() != null) {
			sql.VALUES("nick_name", "#{nickName,jdbcType=VARCHAR}");
		}
		if (record.getAvatarUrl() != null) {
			sql.VALUES("avatar_url", "#{avatarUrl,jdbcType=VARCHAR}");
		}
		if (record.getGender() != null) {
			sql.VALUES("gender", "#{gender,jdbcType=TINYINT}");
		}
		if (record.getCountry() != null) {
			sql.VALUES("country", "#{country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			sql.VALUES("province", "#{province,jdbcType=VARCHAR}");
		}
		if (record.getCity() != null) {
			sql.VALUES("city", "#{city,jdbcType=VARCHAR}");
		}
		if (record.getLanguage() != null) {
			sql.VALUES("language", "#{language,jdbcType=VARCHAR}");
		}
		if (record.getAddtime() != null) {
			sql.VALUES("addtime", "#{addtime,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String selectByExample(UserExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("openid");
		sql.SELECT("unionid");
		sql.SELECT("nick_name");
		sql.SELECT("avatar_url");
		sql.SELECT("gender");
		sql.SELECT("country");
		sql.SELECT("province");
		sql.SELECT("city");
		sql.SELECT("language");
		sql.SELECT("addtime");
		sql.FROM("user");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		User record = (User) parameter.get("record");
		UserExample example = (UserExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("user");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getOpenid() != null) {
			sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.SET("unionid = #{record.unionid,jdbcType=VARCHAR}");
		}
		if (record.getNickName() != null) {
			sql.SET("nick_name = #{record.nickName,jdbcType=VARCHAR}");
		}
		if (record.getAvatarUrl() != null) {
			sql.SET("avatar_url = #{record.avatarUrl,jdbcType=VARCHAR}");
		}
		if (record.getGender() != null) {
			sql.SET("gender = #{record.gender,jdbcType=TINYINT}");
		}
		if (record.getCountry() != null) {
			sql.SET("country = #{record.country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			sql.SET("province = #{record.province,jdbcType=VARCHAR}");
		}
		if (record.getCity() != null) {
			sql.SET("city = #{record.city,jdbcType=VARCHAR}");
		}
		if (record.getLanguage() != null) {
			sql.SET("language = #{record.language,jdbcType=VARCHAR}");
		}
		if (record.getAddtime() != null) {
			sql.SET("addtime = #{record.addtime,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("user");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		sql.SET("unionid = #{record.unionid,jdbcType=VARCHAR}");
		sql.SET("nick_name = #{record.nickName,jdbcType=VARCHAR}");
		sql.SET("avatar_url = #{record.avatarUrl,jdbcType=VARCHAR}");
		sql.SET("gender = #{record.gender,jdbcType=TINYINT}");
		sql.SET("country = #{record.country,jdbcType=VARCHAR}");
		sql.SET("province = #{record.province,jdbcType=VARCHAR}");
		sql.SET("city = #{record.city,jdbcType=VARCHAR}");
		sql.SET("language = #{record.language,jdbcType=VARCHAR}");
		sql.SET("addtime = #{record.addtime,jdbcType=TIMESTAMP}");
		UserExample example = (UserExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(User record) {
		SQL sql = new SQL();
		sql.UPDATE("user");
		if (record.getOpenid() != null) {
			sql.SET("openid = #{openid,jdbcType=VARCHAR}");
		}
		if (record.getUnionid() != null) {
			sql.SET("unionid = #{unionid,jdbcType=VARCHAR}");
		}
		if (record.getNickName() != null) {
			sql.SET("nick_name = #{nickName,jdbcType=VARCHAR}");
		}
		if (record.getAvatarUrl() != null) {
			sql.SET("avatar_url = #{avatarUrl,jdbcType=VARCHAR}");
		}
		if (record.getGender() != null) {
			sql.SET("gender = #{gender,jdbcType=TINYINT}");
		}
		if (record.getCountry() != null) {
			sql.SET("country = #{country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			sql.SET("province = #{province,jdbcType=VARCHAR}");
		}
		if (record.getCity() != null) {
			sql.SET("city = #{city,jdbcType=VARCHAR}");
		}
		if (record.getLanguage() != null) {
			sql.SET("language = #{language,jdbcType=VARCHAR}");
		}
		if (record.getAddtime() != null) {
			sql.SET("addtime = #{addtime,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, UserExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}