package com.github.blovemaple.hura.dal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VortlistoVortoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public VortlistoVortoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdIsNull() {
			addCriterion("vortlisto_id is null");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdIsNotNull() {
			addCriterion("vortlisto_id is not null");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdEqualTo(Long value) {
			addCriterion("vortlisto_id =", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdNotEqualTo(Long value) {
			addCriterion("vortlisto_id <>", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdGreaterThan(Long value) {
			addCriterion("vortlisto_id >", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdGreaterThanOrEqualTo(Long value) {
			addCriterion("vortlisto_id >=", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdLessThan(Long value) {
			addCriterion("vortlisto_id <", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdLessThanOrEqualTo(Long value) {
			addCriterion("vortlisto_id <=", value, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdIn(List<Long> values) {
			addCriterion("vortlisto_id in", values, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdNotIn(List<Long> values) {
			addCriterion("vortlisto_id not in", values, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdBetween(Long value1, Long value2) {
			addCriterion("vortlisto_id between", value1, value2, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andVortlistoIdNotBetween(Long value1, Long value2) {
			addCriterion("vortlisto_id not between", value1, value2, "vortlistoId");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNull() {
			addCriterion("openid is null");
			return (Criteria) this;
		}

		public Criteria andOpenidIsNotNull() {
			addCriterion("openid is not null");
			return (Criteria) this;
		}

		public Criteria andOpenidEqualTo(String value) {
			addCriterion("openid =", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotEqualTo(String value) {
			addCriterion("openid <>", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThan(String value) {
			addCriterion("openid >", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidGreaterThanOrEqualTo(String value) {
			addCriterion("openid >=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThan(String value) {
			addCriterion("openid <", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLessThanOrEqualTo(String value) {
			addCriterion("openid <=", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidLike(String value) {
			addCriterion("openid like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotLike(String value) {
			addCriterion("openid not like", value, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidIn(List<String> values) {
			addCriterion("openid in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotIn(List<String> values) {
			addCriterion("openid not in", values, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidBetween(String value1, String value2) {
			addCriterion("openid between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andOpenidNotBetween(String value1, String value2) {
			addCriterion("openid not between", value1, value2, "openid");
			return (Criteria) this;
		}

		public Criteria andVortoIsNull() {
			addCriterion("vorto is null");
			return (Criteria) this;
		}

		public Criteria andVortoIsNotNull() {
			addCriterion("vorto is not null");
			return (Criteria) this;
		}

		public Criteria andVortoEqualTo(String value) {
			addCriterion("vorto =", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoNotEqualTo(String value) {
			addCriterion("vorto <>", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoGreaterThan(String value) {
			addCriterion("vorto >", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoGreaterThanOrEqualTo(String value) {
			addCriterion("vorto >=", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoLessThan(String value) {
			addCriterion("vorto <", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoLessThanOrEqualTo(String value) {
			addCriterion("vorto <=", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoLike(String value) {
			addCriterion("vorto like", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoNotLike(String value) {
			addCriterion("vorto not like", value, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoIn(List<String> values) {
			addCriterion("vorto in", values, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoNotIn(List<String> values) {
			addCriterion("vorto not in", values, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoBetween(String value1, String value2) {
			addCriterion("vorto between", value1, value2, "vorto");
			return (Criteria) this;
		}

		public Criteria andVortoNotBetween(String value1, String value2) {
			addCriterion("vorto not between", value1, value2, "vorto");
			return (Criteria) this;
		}

		public Criteria andSignifoIsNull() {
			addCriterion("signifo is null");
			return (Criteria) this;
		}

		public Criteria andSignifoIsNotNull() {
			addCriterion("signifo is not null");
			return (Criteria) this;
		}

		public Criteria andSignifoEqualTo(String value) {
			addCriterion("signifo =", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoNotEqualTo(String value) {
			addCriterion("signifo <>", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoGreaterThan(String value) {
			addCriterion("signifo >", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoGreaterThanOrEqualTo(String value) {
			addCriterion("signifo >=", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoLessThan(String value) {
			addCriterion("signifo <", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoLessThanOrEqualTo(String value) {
			addCriterion("signifo <=", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoLike(String value) {
			addCriterion("signifo like", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoNotLike(String value) {
			addCriterion("signifo not like", value, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoIn(List<String> values) {
			addCriterion("signifo in", values, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoNotIn(List<String> values) {
			addCriterion("signifo not in", values, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoBetween(String value1, String value2) {
			addCriterion("signifo between", value1, value2, "signifo");
			return (Criteria) this;
		}

		public Criteria andSignifoNotBetween(String value1, String value2) {
			addCriterion("signifo not between", value1, value2, "signifo");
			return (Criteria) this;
		}

		public Criteria andIsDelIsNull() {
			addCriterion("is_del is null");
			return (Criteria) this;
		}

		public Criteria andIsDelIsNotNull() {
			addCriterion("is_del is not null");
			return (Criteria) this;
		}

		public Criteria andIsDelEqualTo(Boolean value) {
			addCriterion("is_del =", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotEqualTo(Boolean value) {
			addCriterion("is_del <>", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelGreaterThan(Boolean value) {
			addCriterion("is_del >", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_del >=", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelLessThan(Boolean value) {
			addCriterion("is_del <", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
			addCriterion("is_del <=", value, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelIn(List<Boolean> values) {
			addCriterion("is_del in", values, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotIn(List<Boolean> values) {
			addCriterion("is_del not in", values, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
			addCriterion("is_del between", value1, value2, "isDel");
			return (Criteria) this;
		}

		public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_del not between", value1, value2, "isDel");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andModtimeIsNull() {
			addCriterion("modtime is null");
			return (Criteria) this;
		}

		public Criteria andModtimeIsNotNull() {
			addCriterion("modtime is not null");
			return (Criteria) this;
		}

		public Criteria andModtimeEqualTo(Date value) {
			addCriterion("modtime =", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotEqualTo(Date value) {
			addCriterion("modtime <>", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeGreaterThan(Date value) {
			addCriterion("modtime >", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modtime >=", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeLessThan(Date value) {
			addCriterion("modtime <", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeLessThanOrEqualTo(Date value) {
			addCriterion("modtime <=", value, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeIn(List<Date> values) {
			addCriterion("modtime in", values, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotIn(List<Date> values) {
			addCriterion("modtime not in", values, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeBetween(Date value1, Date value2) {
			addCriterion("modtime between", value1, value2, "modtime");
			return (Criteria) this;
		}

		public Criteria andModtimeNotBetween(Date value1, Date value2) {
			addCriterion("modtime not between", value1, value2, "modtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vortlisto_vorto
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}