package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.VortlistoVorto;
import com.github.blovemaple.hura.dal.VortlistoVortoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface VortlistoVortoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@SelectProvider(type = VortlistoVortoSqlProvider.class, method = "countByExample")
	long countByExample(VortlistoVortoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@DeleteProvider(type = VortlistoVortoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(VortlistoVortoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@Delete({ "delete from vortlisto_vorto", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@Insert({ "insert into vortlisto_vorto (vortlisto_id, openid, ", "vorto, signifo, ", "is_del, addtime, modtime)",
			"values (#{vortlistoId,jdbcType=BIGINT}, #{openid,jdbcType=VARCHAR}, ",
			"#{vorto,jdbcType=VARCHAR}, #{signifo,jdbcType=VARCHAR}, ",
			"#{isDel,jdbcType=BIT}, #{addtime,jdbcType=TIMESTAMP}, #{modtime,jdbcType=TIMESTAMP})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(VortlistoVorto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@InsertProvider(type = VortlistoVortoSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insertSelective(VortlistoVorto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@SelectProvider(type = VortlistoVortoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "vortlisto_id", property = "vortlistoId", jdbcType = JdbcType.BIGINT),
			@Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "vorto", property = "vorto", jdbcType = JdbcType.VARCHAR),
			@Result(column = "signifo", property = "signifo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_del", property = "isDel", jdbcType = JdbcType.BIT),
			@Result(column = "addtime", property = "addtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	List<VortlistoVorto> selectByExample(VortlistoVortoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@Select({ "select", "id, vortlisto_id, openid, vorto, signifo, is_del, addtime, modtime", "from vortlisto_vorto",
			"where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "vortlisto_id", property = "vortlistoId", jdbcType = JdbcType.BIGINT),
			@Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "vorto", property = "vorto", jdbcType = JdbcType.VARCHAR),
			@Result(column = "signifo", property = "signifo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_del", property = "isDel", jdbcType = JdbcType.BIT),
			@Result(column = "addtime", property = "addtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	VortlistoVorto selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoVortoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") VortlistoVorto record,
			@Param("example") VortlistoVortoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoVortoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") VortlistoVorto record, @Param("example") VortlistoVortoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoVortoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(VortlistoVorto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto_vorto
	 * @mbg.generated
	 */
	@Update({ "update vortlisto_vorto", "set vortlisto_id = #{vortlistoId,jdbcType=BIGINT},",
			"openid = #{openid,jdbcType=VARCHAR},", "vorto = #{vorto,jdbcType=VARCHAR},",
			"signifo = #{signifo,jdbcType=VARCHAR},", "is_del = #{isDel,jdbcType=BIT},",
			"addtime = #{addtime,jdbcType=TIMESTAMP},", "modtime = #{modtime,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(VortlistoVorto record);
}