package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.Vortlisto;
import com.github.blovemaple.hura.dal.VortlistoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface VortlistoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@SelectProvider(type = VortlistoSqlProvider.class, method = "countByExample")
	long countByExample(VortlistoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@DeleteProvider(type = VortlistoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(VortlistoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@Delete({ "delete from vortlisto", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@Insert({ "insert into vortlisto (openid, name, ", "is_del, addtime, modtime)",
			"values (#{openid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{isDel,jdbcType=BIT}, #{addtime,jdbcType=TIMESTAMP}, #{modtime,jdbcType=TIMESTAMP})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(Vortlisto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@InsertProvider(type = VortlistoSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insertSelective(Vortlisto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@SelectProvider(type = VortlistoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_del", property = "isDel", jdbcType = JdbcType.BIT),
			@Result(column = "addtime", property = "addtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	List<Vortlisto> selectByExample(VortlistoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@Select({ "select", "id, openid, name, is_del, addtime, modtime", "from vortlisto",
			"where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "openid", property = "openid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_del", property = "isDel", jdbcType = JdbcType.BIT),
			@Result(column = "addtime", property = "addtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modtime", property = "modtime", jdbcType = JdbcType.TIMESTAMP) })
	Vortlisto selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Vortlisto record, @Param("example") VortlistoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Vortlisto record, @Param("example") VortlistoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@UpdateProvider(type = VortlistoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Vortlisto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	@Update({ "update vortlisto", "set openid = #{openid,jdbcType=VARCHAR},", "name = #{name,jdbcType=VARCHAR},",
			"is_del = #{isDel,jdbcType=BIT},", "addtime = #{addtime,jdbcType=TIMESTAMP},",
			"modtime = #{modtime,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(Vortlisto record);
}