package com.github.blovemaple.hura.dal;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vortlisto_vorto
 */
public class VortlistoVorto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.vortlisto_id
	 * @mbg.generated
	 */
	private Long vortlistoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.vorto
	 * @mbg.generated
	 */
	private String vorto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.signifo
	 * @mbg.generated
	 */
	private String signifo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.is_del
	 * @mbg.generated
	 */
	private Boolean isDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.addtime
	 * @mbg.generated
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto_vorto.modtime
	 * @mbg.generated
	 */
	private Date modtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.id
	 * @return  the value of vortlisto_vorto.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.id
	 * @param id  the value for vortlisto_vorto.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.vortlisto_id
	 * @return  the value of vortlisto_vorto.vortlisto_id
	 * @mbg.generated
	 */
	public Long getVortlistoId() {
		return vortlistoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.vortlisto_id
	 * @param vortlistoId  the value for vortlisto_vorto.vortlisto_id
	 * @mbg.generated
	 */
	public void setVortlistoId(Long vortlistoId) {
		this.vortlistoId = vortlistoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.openid
	 * @return  the value of vortlisto_vorto.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.openid
	 * @param openid  the value for vortlisto_vorto.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.vorto
	 * @return  the value of vortlisto_vorto.vorto
	 * @mbg.generated
	 */
	public String getVorto() {
		return vorto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.vorto
	 * @param vorto  the value for vortlisto_vorto.vorto
	 * @mbg.generated
	 */
	public void setVorto(String vorto) {
		this.vorto = vorto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.signifo
	 * @return  the value of vortlisto_vorto.signifo
	 * @mbg.generated
	 */
	public String getSignifo() {
		return signifo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.signifo
	 * @param signifo  the value for vortlisto_vorto.signifo
	 * @mbg.generated
	 */
	public void setSignifo(String signifo) {
		this.signifo = signifo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.is_del
	 * @return  the value of vortlisto_vorto.is_del
	 * @mbg.generated
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.is_del
	 * @param isDel  the value for vortlisto_vorto.is_del
	 * @mbg.generated
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.addtime
	 * @return  the value of vortlisto_vorto.addtime
	 * @mbg.generated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.addtime
	 * @param addtime  the value for vortlisto_vorto.addtime
	 * @mbg.generated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto_vorto.modtime
	 * @return  the value of vortlisto_vorto.modtime
	 * @mbg.generated
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto_vorto.modtime
	 * @param modtime  the value for vortlisto_vorto.modtime
	 * @mbg.generated
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}
}