package com.github.blovemaple.hura.dal;

import com.github.blovemaple.hura.dal.Vortlisto;
import com.github.blovemaple.hura.dal.VortlistoExample.Criteria;
import com.github.blovemaple.hura.dal.VortlistoExample.Criterion;
import com.github.blovemaple.hura.dal.VortlistoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class VortlistoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String countByExample(VortlistoExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("vortlisto");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String deleteByExample(VortlistoExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("vortlisto");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String insertSelective(Vortlisto record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("vortlisto");
		if (record.getOpenid() != null) {
			sql.VALUES("openid", "#{openid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getIsDel() != null) {
			sql.VALUES("is_del", "#{isDel,jdbcType=BIT}");
		}
		if (record.getAddtime() != null) {
			sql.VALUES("addtime", "#{addtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModtime() != null) {
			sql.VALUES("modtime", "#{modtime,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String selectByExample(VortlistoExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("openid");
		sql.SELECT("name");
		sql.SELECT("is_del");
		sql.SELECT("addtime");
		sql.SELECT("modtime");
		sql.FROM("vortlisto");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Vortlisto record = (Vortlisto) parameter.get("record");
		VortlistoExample example = (VortlistoExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("vortlisto");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getOpenid() != null) {
			sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getIsDel() != null) {
			sql.SET("is_del = #{record.isDel,jdbcType=BIT}");
		}
		if (record.getAddtime() != null) {
			sql.SET("addtime = #{record.addtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModtime() != null) {
			sql.SET("modtime = #{record.modtime,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("vortlisto");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("openid = #{record.openid,jdbcType=VARCHAR}");
		sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		sql.SET("is_del = #{record.isDel,jdbcType=BIT}");
		sql.SET("addtime = #{record.addtime,jdbcType=TIMESTAMP}");
		sql.SET("modtime = #{record.modtime,jdbcType=TIMESTAMP}");
		VortlistoExample example = (VortlistoExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(Vortlisto record) {
		SQL sql = new SQL();
		sql.UPDATE("vortlisto");
		if (record.getOpenid() != null) {
			sql.SET("openid = #{openid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.SET("name = #{name,jdbcType=VARCHAR}");
		}
		if (record.getIsDel() != null) {
			sql.SET("is_del = #{isDel,jdbcType=BIT}");
		}
		if (record.getAddtime() != null) {
			sql.SET("addtime = #{addtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModtime() != null) {
			sql.SET("modtime = #{modtime,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vortlisto
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, VortlistoExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}