package com.github.blovemaple.hura.dal;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vortlisto
 */
public class Vortlisto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.is_del
	 * @mbg.generated
	 */
	private Boolean isDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.addtime
	 * @mbg.generated
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vortlisto.modtime
	 * @mbg.generated
	 */
	private Date modtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.id
	 * @return  the value of vortlisto.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.id
	 * @param id  the value for vortlisto.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.openid
	 * @return  the value of vortlisto.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.openid
	 * @param openid  the value for vortlisto.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.name
	 * @return  the value of vortlisto.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.name
	 * @param name  the value for vortlisto.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.is_del
	 * @return  the value of vortlisto.is_del
	 * @mbg.generated
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.is_del
	 * @param isDel  the value for vortlisto.is_del
	 * @mbg.generated
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.addtime
	 * @return  the value of vortlisto.addtime
	 * @mbg.generated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.addtime
	 * @param addtime  the value for vortlisto.addtime
	 * @mbg.generated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vortlisto.modtime
	 * @return  the value of vortlisto.modtime
	 * @mbg.generated
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vortlisto.modtime
	 * @param modtime  the value for vortlisto.modtime
	 * @mbg.generated
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}
}