package com.github.blovemaple.hura.dal;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vorto5000
 */
public class Vorto5000 {

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.id")
	private Integer id;
	/**
	 * Database Column Remarks: 词根
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.radiko")
	private String radiko;
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.kruda")
	private String kruda;
	/**
	 * Database Column Remarks: 词义
	 */
	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.signifo")
	private String signifo;

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.id")
	public Integer getId() {
		return id;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.id")
	public void setId(Integer id) {
		this.id = id;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.radiko")
	public String getRadiko() {
		return radiko;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.radiko")
	public void setRadiko(String radiko) {
		this.radiko = radiko;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.kruda")
	public String getKruda() {
		return kruda;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.kruda")
	public void setKruda(String kruda) {
		this.kruda = kruda;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.signifo")
	public String getSignifo() {
		return signifo;
	}

	@Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: vorto5000.signifo")
	public void setSignifo(String signifo) {
		this.signifo = signifo;
	}
}